import Database from "better-sqlite3";
import fs from "fs";
import type { SentenceRecord, AnalysisResult, SentenceTag } from "./types";
import { getDataDir, getDatabasePath } from "./storage-paths";

let db: Database.Database | null = null;

/**
 * Get or create the database instance (singleton).
 */
function getDb(): Database.Database {
  if (!db) {
    const dbDir = getDataDir();
    const dbPath = getDatabasePath();

    // Ensure the data directory exists
    if (!fs.existsSync(dbDir)) {
      fs.mkdirSync(dbDir, { recursive: true });
    }
    db = new Database(dbPath);
    // Enable WAL mode for better concurrent read performance
    db.pragma("journal_mode = WAL");
    // Create tables on first connection
    createTables(db);
  }
  return db;
}

/**
 * Create the sentences table if it doesn't exist.
 */
function createTables(database: Database.Database): void {
  database.exec(`
    CREATE TABLE IF NOT EXISTS sentences (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      sentence TEXT NOT NULL UNIQUE,
      corrected_sentence TEXT NOT NULL,
      analysis TEXT NOT NULL,
      audio_filename TEXT,
      tag_type TEXT,
      tag_name TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);
}

/**
 * Initialize the database — ensures the connection is established and tables are created.
 * Can be called explicitly to eagerly initialize, or it will be called lazily on first query.
 * When called after _resetForTesting, creates tables on the provided test database.
 * Requirements: 5.1
 */
export function initDatabase(): void {
  const database = db ?? getDb();
  createTables(database);
  migrateAddCorrectedSentence(database);
  migrateAddTagColumns(database);
}

/**
 * Migration: Add corrected_sentence column to existing tables.
 * Uses try/catch because ALTER TABLE will fail if the column already exists, which is fine.
 * Then backfills existing rows by setting corrected_sentence = sentence where it's NULL.
 * Requirements: 2.6
 */
function migrateAddCorrectedSentence(database: Database.Database): void {
  try {
    database.exec(
      `ALTER TABLE sentences ADD COLUMN corrected_sentence TEXT`
    );
  } catch {
    // Column already exists — ignore
  }
  database.exec(
    `UPDATE sentences SET corrected_sentence = sentence WHERE corrected_sentence IS NULL`
  );
}

/**
 * Migration: Add optional tag_type/tag_name columns for sentence context tags.
 * Ensures partial tag rows are normalized to NULL for both columns.
 */
function migrateAddTagColumns(database: Database.Database): void {
  try {
    database.exec(`ALTER TABLE sentences ADD COLUMN tag_type TEXT`);
  } catch {
    // Column already exists — ignore
  }
  try {
    database.exec(`ALTER TABLE sentences ADD COLUMN tag_name TEXT`);
  } catch {
    // Column already exists — ignore
  }
  database.exec(
    `UPDATE sentences SET tag_type = NULL, tag_name = NULL WHERE tag_type IS NULL OR tag_name IS NULL`
  );
}

/**
 * Parse a raw database row into a SentenceRecord, converting the JSON analysis string
 * back into an AnalysisResult object.
 */
function rowToSentenceRecord(row: {
  id: number;
  sentence: string;
  corrected_sentence: string;
  analysis: string;
  audio_filename: string | null;
  tag_type: string | null;
  tag_name: string | null;
  created_at: string;
}): SentenceRecord {
  const tag: SentenceTag | null =
    row.tag_type && row.tag_name
      ? { type: row.tag_type, name: row.tag_name }
      : null;

  return {
    id: row.id,
    sentence: row.sentence,
    correctedSentence: row.corrected_sentence,
    analysis: JSON.parse(row.analysis) as AnalysisResult,
    audioFilename: row.audio_filename,
    tag,
    createdAt: row.created_at,
  };
}

/**
 * Find a sentence record by its exact text content.
 * Used for duplicate detection — if a sentence already exists, return the cached record.
 * Requirements: 5.3
 */
export function findSentenceByText(
  sentence: string
): SentenceRecord | undefined {
  const database = getDb();
  const row = database
    .prepare(
      "SELECT id, sentence, corrected_sentence, analysis, audio_filename, tag_type, tag_name, created_at FROM sentences WHERE sentence = ?"
    )
    .get(sentence) as
    | {
        id: number;
        sentence: string;
        corrected_sentence: string;
        analysis: string;
        audio_filename: string | null;
        tag_type: string | null;
        tag_name: string | null;
        created_at: string;
      }
    | undefined;

  if (!row) return undefined;
  return rowToSentenceRecord(row);
}

/**
 * Insert a new sentence record into the database.
 * Accepts a record without the id field (auto-generated by SQLite).
 * Returns the complete SentenceRecord with the assigned id.
 * Requirements: 5.1
 */
export function insertSentence(
  record: Omit<SentenceRecord, "id">
): SentenceRecord {
  const database = getDb();
  const stmt = database.prepare(
    "INSERT INTO sentences (sentence, corrected_sentence, analysis, audio_filename, tag_type, tag_name, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)"
  );
  const result = stmt.run(
    record.sentence,
    record.correctedSentence,
    JSON.stringify(record.analysis),
    record.audioFilename,
    record.tag?.type ?? null,
    record.tag?.name ?? null,
    record.createdAt
  );

  return {
    id: result.lastInsertRowid as number,
    sentence: record.sentence,
    correctedSentence: record.correctedSentence,
    analysis: record.analysis,
    audioFilename: record.audioFilename,
    tag: record.tag ?? null,
    createdAt: record.createdAt,
  };
}

/**
 * Retrieve all sentence records, ordered by created_at descending (newest first).
 * Requirements: 5.2, 7.2
 */
export function getAllSentences(): SentenceRecord[] {
  const database = getDb();
  const rows = database
    .prepare(
      "SELECT id, sentence, corrected_sentence, analysis, audio_filename, tag_type, tag_name, created_at FROM sentences ORDER BY created_at DESC"
    )
    .all() as Array<{
    id: number;
    sentence: string;
    corrected_sentence: string;
    analysis: string;
    audio_filename: string | null;
    tag_type: string | null;
    tag_name: string | null;
    created_at: string;
  }>;

  return rows.map(rowToSentenceRecord);
}

/**
 * Retrieve a single sentence record by its id.
 * Returns undefined if no record exists with the given id.
 * Requirements: 7.3
 */
export function getSentenceById(id: number): SentenceRecord | undefined {
  const database = getDb();
  const row = database
    .prepare(
      "SELECT id, sentence, corrected_sentence, analysis, audio_filename, tag_type, tag_name, created_at FROM sentences WHERE id = ?"
    )
    .get(id) as
    | {
        id: number;
        sentence: string;
        corrected_sentence: string;
        analysis: string;
        audio_filename: string | null;
        tag_type: string | null;
        tag_name: string | null;
        created_at: string;
      }
    | undefined;

  if (!row) return undefined;
  return rowToSentenceRecord(row);
}

/**
 * Update or clear the context tag for a sentence by id.
 * Returns the updated record, or undefined if the id does not exist.
 */
export function updateSentenceTag(
  id: number,
  tag: SentenceTag | null
): SentenceRecord | undefined {
  const existing = getSentenceById(id);
  if (!existing) return undefined;

  const database = getDb();
  database
    .prepare("UPDATE sentences SET tag_type = ?, tag_name = ? WHERE id = ?")
    .run(tag?.type ?? null, tag?.name ?? null, id);

  return getSentenceById(id);
}

/**
 * Close the database connection. Useful for testing cleanup.
 */
export function closeDatabase(): void {
  if (db) {
    db.close();
    db = null;
  }
}

/**
 * Reset the database singleton — used for testing to allow re-initialization
 * with a different database instance (e.g., in-memory).
 * If a testDb is provided, tables are NOT automatically created —
 * call initDatabase() after this to set up the schema.
 */
export function _resetForTesting(testDb?: Database.Database): void {
  if (db) {
    try {
      db.close();
    } catch {
      // Ignore close errors during testing
    }
  }
  db = testDb ?? null;
}
